DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS health_checks CASCADE;
DROP TABLE IF EXISTS resolved_routes CASCADE;
DROP TABLE IF EXISTS routing_rules CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;
DROP TABLE IF EXISTS interfaces CASCADE;
DROP TABLE IF EXISTS vpn_providers CASCADE;

DROP TYPE IF EXISTS check_status;
DROP TYPE IF EXISTS interface_state;
DROP TYPE IF EXISTS interface_type;
DROP TYPE IF EXISTS rule_type;
DROP TYPE IF EXISTS provider_type;

DROP EXTENSION IF EXISTS "pgcrypto";
