// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health_checks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHealthCheck = `-- name: CreateHealthCheck :one
INSERT INTO health_checks (provider_id, status, latency_ms, error)
VALUES ($1, $2, $3, $4)
RETURNING id, provider_id, status, latency_ms, error, checked_at
`

type CreateHealthCheckParams struct {
	ProviderID pgtype.UUID `json:"provider_id"`
	Status     CheckStatus `json:"status"`
	LatencyMs  pgtype.Int4 `json:"latency_ms"`
	Error      pgtype.Text `json:"error"`
}

// Проверки здоровья
func (q *Queries) CreateHealthCheck(ctx context.Context, arg CreateHealthCheckParams) (HealthCheck, error) {
	row := q.db.QueryRow(ctx, createHealthCheck,
		arg.ProviderID,
		arg.Status,
		arg.LatencyMs,
		arg.Error,
	)
	var i HealthCheck
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Status,
		&i.LatencyMs,
		&i.Error,
		&i.CheckedAt,
	)
	return i, err
}

const getLatestHealthCheck = `-- name: GetLatestHealthCheck :one
SELECT id, provider_id, status, latency_ms, error, checked_at FROM health_checks
WHERE provider_id = $1
ORDER BY checked_at DESC
LIMIT 1
`

func (q *Queries) GetLatestHealthCheck(ctx context.Context, providerID pgtype.UUID) (HealthCheck, error) {
	row := q.db.QueryRow(ctx, getLatestHealthCheck, providerID)
	var i HealthCheck
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Status,
		&i.LatencyMs,
		&i.Error,
		&i.CheckedAt,
	)
	return i, err
}

const getProviderUptime = `-- name: GetProviderUptime :one
SELECT
    COUNT(*) FILTER (WHERE status = 'up')::float / GREATEST(COUNT(*), 1)::float * 100 as uptime_pct,
    COUNT(*) FILTER (WHERE status = 'down')::int as failures,
    COUNT(*)::int as total_checks
FROM health_checks
WHERE provider_id = $1
  AND checked_at > now() - $2::interval
`

type GetProviderUptimeParams struct {
	ProviderID pgtype.UUID     `json:"provider_id"`
	Column2    pgtype.Interval `json:"column_2"`
}

type GetProviderUptimeRow struct {
	UptimePct   int32 `json:"uptime_pct"`
	Failures    int32 `json:"failures"`
	TotalChecks int32 `json:"total_checks"`
}

func (q *Queries) GetProviderUptime(ctx context.Context, arg GetProviderUptimeParams) (GetProviderUptimeRow, error) {
	row := q.db.QueryRow(ctx, getProviderUptime, arg.ProviderID, arg.Column2)
	var i GetProviderUptimeRow
	err := row.Scan(&i.UptimePct, &i.Failures, &i.TotalChecks)
	return i, err
}

const listHealthChecks = `-- name: ListHealthChecks :many
SELECT id, provider_id, status, latency_ms, error, checked_at FROM health_checks
WHERE provider_id = $1
ORDER BY checked_at DESC
LIMIT $2
`

type ListHealthChecksParams struct {
	ProviderID pgtype.UUID `json:"provider_id"`
	Limit      int32       `json:"limit"`
}

func (q *Queries) ListHealthChecks(ctx context.Context, arg ListHealthChecksParams) ([]HealthCheck, error) {
	rows, err := q.db.Query(ctx, listHealthChecks, arg.ProviderID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HealthCheck{}
	for rows.Next() {
		var i HealthCheck
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Status,
			&i.LatencyMs,
			&i.Error,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
