// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: interfaces.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteInterface = `-- name: DeleteInterface :exec
DELETE FROM interfaces WHERE id = $1
`

func (q *Queries) DeleteInterface(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInterface, id)
	return err
}

const getInterface = `-- name: GetInterface :one
SELECT id, name, provider_id, type, state, local_ip, config, created_at, updated_at FROM interfaces WHERE id = $1
`

func (q *Queries) GetInterface(ctx context.Context, id pgtype.UUID) (Interface, error) {
	row := q.db.QueryRow(ctx, getInterface, id)
	var i Interface
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderID,
		&i.Type,
		&i.State,
		&i.LocalIp,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInterfaceByName = `-- name: GetInterfaceByName :one
SELECT id, name, provider_id, type, state, local_ip, config, created_at, updated_at FROM interfaces WHERE name = $1
`

func (q *Queries) GetInterfaceByName(ctx context.Context, name string) (Interface, error) {
	row := q.db.QueryRow(ctx, getInterfaceByName, name)
	var i Interface
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderID,
		&i.Type,
		&i.State,
		&i.LocalIp,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInterfaces = `-- name: ListInterfaces :many
SELECT id, name, provider_id, type, state, local_ip, config, created_at, updated_at FROM interfaces ORDER BY name ASC
`

// Интерфейсы
func (q *Queries) ListInterfaces(ctx context.Context) ([]Interface, error) {
	rows, err := q.db.Query(ctx, listInterfaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Interface{}
	for rows.Next() {
		var i Interface
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProviderID,
			&i.Type,
			&i.State,
			&i.LocalIp,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInterfaceState = `-- name: UpdateInterfaceState :one
UPDATE interfaces SET state = $2, updated_at = now() WHERE id = $1 RETURNING id, name, provider_id, type, state, local_ip, config, created_at, updated_at
`

type UpdateInterfaceStateParams struct {
	ID    pgtype.UUID    `json:"id"`
	State InterfaceState `json:"state"`
}

func (q *Queries) UpdateInterfaceState(ctx context.Context, arg UpdateInterfaceStateParams) (Interface, error) {
	row := q.db.QueryRow(ctx, updateInterfaceState, arg.ID, arg.State)
	var i Interface
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderID,
		&i.Type,
		&i.State,
		&i.LocalIp,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertInterface = `-- name: UpsertInterface :one
INSERT INTO interfaces (name, provider_id, type, state, local_ip, config)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (name) DO UPDATE
SET provider_id = COALESCE($2, interfaces.provider_id),
    type        = COALESCE($3, interfaces.type),
    state       = COALESCE($4, interfaces.state),
    local_ip    = COALESCE($5, interfaces.local_ip),
    config      = COALESCE($6, interfaces.config),
    updated_at  = now()
RETURNING id, name, provider_id, type, state, local_ip, config, created_at, updated_at
`

type UpsertInterfaceParams struct {
	Name       string         `json:"name"`
	ProviderID pgtype.UUID    `json:"provider_id"`
	Type       InterfaceType  `json:"type"`
	State      InterfaceState `json:"state"`
	LocalIp    *netip.Addr    `json:"local_ip"`
	Config     []byte         `json:"config"`
}

func (q *Queries) UpsertInterface(ctx context.Context, arg UpsertInterfaceParams) (Interface, error) {
	row := q.db.QueryRow(ctx, upsertInterface,
		arg.Name,
		arg.ProviderID,
		arg.Type,
		arg.State,
		arg.LocalIp,
		arg.Config,
	)
	var i Interface
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderID,
		&i.Type,
		&i.State,
		&i.LocalIp,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
