// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type CheckStatus string

const (
	CheckStatusUp       CheckStatus = "up"
	CheckStatusDown     CheckStatus = "down"
	CheckStatusDegraded CheckStatus = "degraded"
)

func (e *CheckStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CheckStatus(s)
	case string:
		*e = CheckStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CheckStatus: %T", src)
	}
	return nil
}

type NullCheckStatus struct {
	CheckStatus CheckStatus `json:"check_status"`
	Valid       bool        `json:"valid"` // Valid is true if CheckStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCheckStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CheckStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CheckStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCheckStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CheckStatus), nil
}

type InterfaceState string

const (
	InterfaceStateUp    InterfaceState = "up"
	InterfaceStateDown  InterfaceState = "down"
	InterfaceStateError InterfaceState = "error"
)

func (e *InterfaceState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InterfaceState(s)
	case string:
		*e = InterfaceState(s)
	default:
		return fmt.Errorf("unsupported scan type for InterfaceState: %T", src)
	}
	return nil
}

type NullInterfaceState struct {
	InterfaceState InterfaceState `json:"interface_state"`
	Valid          bool           `json:"valid"` // Valid is true if InterfaceState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInterfaceState) Scan(value interface{}) error {
	if value == nil {
		ns.InterfaceState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InterfaceState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInterfaceState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InterfaceState), nil
}

type InterfaceType string

const (
	InterfaceTypeAmneziawg InterfaceType = "amneziawg"
	InterfaceTypeWireguard InterfaceType = "wireguard"
	InterfaceTypeTun       InterfaceType = "tun"
)

func (e *InterfaceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InterfaceType(s)
	case string:
		*e = InterfaceType(s)
	default:
		return fmt.Errorf("unsupported scan type for InterfaceType: %T", src)
	}
	return nil
}

type NullInterfaceType struct {
	InterfaceType InterfaceType `json:"interface_type"`
	Valid         bool          `json:"valid"` // Valid is true if InterfaceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInterfaceType) Scan(value interface{}) error {
	if value == nil {
		ns.InterfaceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InterfaceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInterfaceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InterfaceType), nil
}

type ProviderType string

const (
	ProviderTypeAmneziawg   ProviderType = "amneziawg"
	ProviderTypeWireguard   ProviderType = "wireguard"
	ProviderTypeVless       ProviderType = "vless"
	ProviderTypeHysteria2   ProviderType = "hysteria2"
	ProviderTypeTuic        ProviderType = "tuic"
	ProviderTypeShadowsocks ProviderType = "shadowsocks"
)

func (e *ProviderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProviderType(s)
	case string:
		*e = ProviderType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProviderType: %T", src)
	}
	return nil
}

type NullProviderType struct {
	ProviderType ProviderType `json:"provider_type"`
	Valid        bool         `json:"valid"` // Valid is true if ProviderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProviderType) Scan(value interface{}) error {
	if value == nil {
		ns.ProviderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProviderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProviderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProviderType), nil
}

type RuleType string

const (
	RuleTypeDomain        RuleType = "domain"
	RuleTypeDomainSuffix  RuleType = "domain_suffix"
	RuleTypeDomainKeyword RuleType = "domain_keyword"
	RuleTypeIp            RuleType = "ip"
	RuleTypeCidr          RuleType = "cidr"
	RuleTypeAsn           RuleType = "asn"
	RuleTypeGeoip         RuleType = "geoip"
	RuleTypeGeosite       RuleType = "geosite"
)

func (e *RuleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RuleType(s)
	case string:
		*e = RuleType(s)
	default:
		return fmt.Errorf("unsupported scan type for RuleType: %T", src)
	}
	return nil
}

type NullRuleType struct {
	RuleType RuleType `json:"rule_type"`
	Valid    bool     `json:"valid"` // Valid is true if RuleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRuleType) Scan(value interface{}) error {
	if value == nil {
		ns.RuleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RuleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRuleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RuleType), nil
}

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Payload    []byte             `json:"payload"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type HealthCheck struct {
	ID         pgtype.UUID        `json:"id"`
	ProviderID pgtype.UUID        `json:"provider_id"`
	Status     CheckStatus        `json:"status"`
	LatencyMs  pgtype.Int4        `json:"latency_ms"`
	Error      pgtype.Text        `json:"error"`
	CheckedAt  pgtype.Timestamptz `json:"checked_at"`
}

type Interface struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	ProviderID pgtype.UUID        `json:"provider_id"`
	Type       InterfaceType      `json:"type"`
	State      InterfaceState     `json:"state"`
	LocalIp    *netip.Addr        `json:"local_ip"`
	Config     []byte             `json:"config"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Profile struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsDefault   bool               `json:"is_default"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ResolvedRoute struct {
	ID        pgtype.UUID        `json:"id"`
	RuleID    pgtype.UUID        `json:"rule_id"`
	Ip        netip.Addr         `json:"ip"`
	LastSeen  pgtype.Timestamptz `json:"last_seen"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RoutingRule struct {
	ID          pgtype.UUID        `json:"id"`
	ProfileID   pgtype.UUID        `json:"profile_id"`
	ProviderID  pgtype.UUID        `json:"provider_id"`
	RuleType    RuleType           `json:"rule_type"`
	Value       string             `json:"value"`
	Enabled     bool               `json:"enabled"`
	Priority    int32              `json:"priority"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type VpnProvider struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	ProviderType ProviderType       `json:"provider_type"`
	Config       []byte             `json:"config"`
	Enabled      bool               `json:"enabled"`
	Priority     int32              `json:"priority"`
	HealthHost   pgtype.Text        `json:"health_host"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
