// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (name, description, is_default)
VALUES ($1, $2, $3)
RETURNING id, name, description, is_default, created_at, updated_at
`

type CreateProfileParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsDefault   bool        `json:"is_default"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile, arg.Name, arg.Description, arg.IsDefault)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles WHERE id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfile, id)
	return err
}

const getDefaultProfile = `-- name: GetDefaultProfile :one
SELECT id, name, description, is_default, created_at, updated_at FROM profiles WHERE is_default = true LIMIT 1
`

func (q *Queries) GetDefaultProfile(ctx context.Context) (Profile, error) {
	row := q.db.QueryRow(ctx, getDefaultProfile)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT id, name, description, is_default, created_at, updated_at FROM profiles WHERE id = $1
`

func (q *Queries) GetProfile(ctx context.Context, id pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, name, description, is_default, created_at, updated_at FROM profiles ORDER BY name ASC
`

// Профили
func (q *Queries) ListProfiles(ctx context.Context) ([]Profile, error) {
	rows, err := q.db.Query(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Profile{}
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetDefaultProfile = `-- name: ResetDefaultProfile :exec
UPDATE profiles SET is_default = false WHERE is_default = true
`

func (q *Queries) ResetDefaultProfile(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetDefaultProfile)
	return err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET name        = COALESCE($2, name),
    description = COALESCE($3, description),
    is_default  = COALESCE($4, is_default),
    updated_at  = now()
WHERE id = $1
RETURNING id, name, description, is_default, created_at, updated_at
`

type UpdateProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsDefault   bool        `json:"is_default"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsDefault,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
