// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO vpn_providers (name, provider_type, config, enabled, priority, health_host)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, provider_type, config, enabled, priority, health_host, created_at, updated_at
`

type CreateProviderParams struct {
	Name         string       `json:"name"`
	ProviderType ProviderType `json:"provider_type"`
	Config       []byte       `json:"config"`
	Enabled      bool         `json:"enabled"`
	Priority     int32        `json:"priority"`
	HealthHost   pgtype.Text  `json:"health_host"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (VpnProvider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.Name,
		arg.ProviderType,
		arg.Config,
		arg.Enabled,
		arg.Priority,
		arg.HealthHost,
	)
	var i VpnProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderType,
		&i.Config,
		&i.Enabled,
		&i.Priority,
		&i.HealthHost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProvider = `-- name: DeleteProvider :exec
DELETE FROM vpn_providers WHERE id = $1
`

func (q *Queries) DeleteProvider(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProvider, id)
	return err
}

const getProvider = `-- name: GetProvider :one
SELECT id, name, provider_type, config, enabled, priority, health_host, created_at, updated_at FROM vpn_providers WHERE id = $1
`

func (q *Queries) GetProvider(ctx context.Context, id pgtype.UUID) (VpnProvider, error) {
	row := q.db.QueryRow(ctx, getProvider, id)
	var i VpnProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderType,
		&i.Config,
		&i.Enabled,
		&i.Priority,
		&i.HealthHost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledProviders = `-- name: ListEnabledProviders :many
SELECT id, name, provider_type, config, enabled, priority, health_host, created_at, updated_at FROM vpn_providers WHERE enabled = true ORDER BY priority ASC NULLS LAST
`

func (q *Queries) ListEnabledProviders(ctx context.Context) ([]VpnProvider, error) {
	rows, err := q.db.Query(ctx, listEnabledProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VpnProvider{}
	for rows.Next() {
		var i VpnProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProviderType,
			&i.Config,
			&i.Enabled,
			&i.Priority,
			&i.HealthHost,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviders = `-- name: ListProviders :many
SELECT id, name, provider_type, config, enabled, priority, health_host, created_at, updated_at FROM vpn_providers ORDER BY priority ASC NULLS LAST, name ASC
`

// Провайдеры
func (q *Queries) ListProviders(ctx context.Context) ([]VpnProvider, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VpnProvider{}
	for rows.Next() {
		var i VpnProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProviderType,
			&i.Config,
			&i.Enabled,
			&i.Priority,
			&i.HealthHost,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE vpn_providers
SET name         = COALESCE($2, name),
    provider_type = COALESCE($3, provider_type),
    config       = COALESCE($4, config),
    enabled      = COALESCE($5, enabled),
    priority     = COALESCE($6, priority),
    health_host  = COALESCE($7, health_host),
    updated_at   = now()
WHERE id = $1
RETURNING id, name, provider_type, config, enabled, priority, health_host, created_at, updated_at
`

type UpdateProviderParams struct {
	ID           pgtype.UUID  `json:"id"`
	Name         string       `json:"name"`
	ProviderType ProviderType `json:"provider_type"`
	Config       []byte       `json:"config"`
	Enabled      bool         `json:"enabled"`
	Priority     int32        `json:"priority"`
	HealthHost   pgtype.Text  `json:"health_host"`
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (VpnProvider, error) {
	row := q.db.QueryRow(ctx, updateProvider,
		arg.ID,
		arg.Name,
		arg.ProviderType,
		arg.Config,
		arg.Enabled,
		arg.Priority,
		arg.HealthHost,
	)
	var i VpnProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderType,
		&i.Config,
		&i.Enabled,
		&i.Priority,
		&i.HealthHost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
