// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Журнал аудита
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	// Проверки здоровья
	CreateHealthCheck(ctx context.Context, arg CreateHealthCheckParams) (HealthCheck, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (VpnProvider, error)
	CreateRule(ctx context.Context, arg CreateRuleParams) (RoutingRule, error)
	DeleteInterface(ctx context.Context, id pgtype.UUID) error
	DeleteProfile(ctx context.Context, id pgtype.UUID) error
	DeleteProvider(ctx context.Context, id pgtype.UUID) error
	DeleteResolvedRoute(ctx context.Context, id pgtype.UUID) error
	DeleteResolvedRoutesByRule(ctx context.Context, ruleID pgtype.UUID) error
	DeleteRule(ctx context.Context, id pgtype.UUID) error
	DeleteStaleResolvedRoutes(ctx context.Context, dollar_1 pgtype.Interval) error
	GetDefaultProfile(ctx context.Context) (Profile, error)
	GetInterface(ctx context.Context, id pgtype.UUID) (Interface, error)
	GetInterfaceByName(ctx context.Context, name string) (Interface, error)
	GetLatestHealthCheck(ctx context.Context, providerID pgtype.UUID) (HealthCheck, error)
	GetProfile(ctx context.Context, id pgtype.UUID) (Profile, error)
	GetProvider(ctx context.Context, id pgtype.UUID) (VpnProvider, error)
	GetProviderUptime(ctx context.Context, arg GetProviderUptimeParams) (GetProviderUptimeRow, error)
	GetRule(ctx context.Context, id pgtype.UUID) (RoutingRule, error)
	GetRulesByProvider(ctx context.Context, providerID pgtype.UUID) ([]RoutingRule, error)
	ListAllResolvedIps(ctx context.Context) ([]ListAllResolvedIpsRow, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error)
	ListEnabledDomainRules(ctx context.Context) ([]ListEnabledDomainRulesRow, error)
	ListEnabledProviders(ctx context.Context) ([]VpnProvider, error)
	ListEnabledRulesByProfile(ctx context.Context, profileID pgtype.UUID) ([]ListEnabledRulesByProfileRow, error)
	ListHealthChecks(ctx context.Context, arg ListHealthChecksParams) ([]HealthCheck, error)
	// Интерфейсы
	ListInterfaces(ctx context.Context) ([]Interface, error)
	// Профили
	ListProfiles(ctx context.Context) ([]Profile, error)
	// Провайдеры
	ListProviders(ctx context.Context) ([]VpnProvider, error)
	// Разрешённые маршруты
	ListResolvedRoutesByRule(ctx context.Context, ruleID pgtype.UUID) ([]ResolvedRoute, error)
	// Правила маршрутизации
	ListRulesByProfile(ctx context.Context, profileID pgtype.UUID) ([]RoutingRule, error)
	ResetDefaultProfile(ctx context.Context) error
	UpdateInterfaceState(ctx context.Context, arg UpdateInterfaceStateParams) (Interface, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error)
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) (VpnProvider, error)
	UpdateRule(ctx context.Context, arg UpdateRuleParams) (RoutingRule, error)
	UpsertInterface(ctx context.Context, arg UpsertInterfaceParams) (Interface, error)
	UpsertResolvedRoute(ctx context.Context, arg UpsertResolvedRouteParams) (ResolvedRoute, error)
}

var _ Querier = (*Queries)(nil)
