// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resolved_routes.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteResolvedRoute = `-- name: DeleteResolvedRoute :exec
DELETE FROM resolved_routes WHERE id = $1
`

func (q *Queries) DeleteResolvedRoute(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteResolvedRoute, id)
	return err
}

const deleteResolvedRoutesByRule = `-- name: DeleteResolvedRoutesByRule :exec
DELETE FROM resolved_routes WHERE rule_id = $1
`

func (q *Queries) DeleteResolvedRoutesByRule(ctx context.Context, ruleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteResolvedRoutesByRule, ruleID)
	return err
}

const deleteStaleResolvedRoutes = `-- name: DeleteStaleResolvedRoutes :exec
DELETE FROM resolved_routes WHERE last_seen < now() - $1::interval
`

func (q *Queries) DeleteStaleResolvedRoutes(ctx context.Context, dollar_1 pgtype.Interval) error {
	_, err := q.db.Exec(ctx, deleteStaleResolvedRoutes, dollar_1)
	return err
}

const listAllResolvedIps = `-- name: ListAllResolvedIps :many
SELECT DISTINCT rr.ip, r.provider_id
FROM resolved_routes rr
JOIN routing_rules r ON rr.rule_id = r.id
WHERE r.enabled = true
`

type ListAllResolvedIpsRow struct {
	Ip         netip.Addr  `json:"ip"`
	ProviderID pgtype.UUID `json:"provider_id"`
}

func (q *Queries) ListAllResolvedIps(ctx context.Context) ([]ListAllResolvedIpsRow, error) {
	rows, err := q.db.Query(ctx, listAllResolvedIps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllResolvedIpsRow{}
	for rows.Next() {
		var i ListAllResolvedIpsRow
		if err := rows.Scan(&i.Ip, &i.ProviderID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResolvedRoutesByRule = `-- name: ListResolvedRoutesByRule :many
SELECT id, rule_id, ip, last_seen, created_at FROM resolved_routes WHERE rule_id = $1 ORDER BY ip ASC
`

// Разрешённые маршруты
func (q *Queries) ListResolvedRoutesByRule(ctx context.Context, ruleID pgtype.UUID) ([]ResolvedRoute, error) {
	rows, err := q.db.Query(ctx, listResolvedRoutesByRule, ruleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolvedRoute{}
	for rows.Next() {
		var i ResolvedRoute
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.Ip,
			&i.LastSeen,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertResolvedRoute = `-- name: UpsertResolvedRoute :one
INSERT INTO resolved_routes (rule_id, ip, last_seen)
VALUES ($1, $2, now())
ON CONFLICT (rule_id, ip) DO UPDATE
SET last_seen = now()
RETURNING id, rule_id, ip, last_seen, created_at
`

type UpsertResolvedRouteParams struct {
	RuleID pgtype.UUID `json:"rule_id"`
	Ip     netip.Addr  `json:"ip"`
}

func (q *Queries) UpsertResolvedRoute(ctx context.Context, arg UpsertResolvedRouteParams) (ResolvedRoute, error) {
	row := q.db.QueryRow(ctx, upsertResolvedRoute, arg.RuleID, arg.Ip)
	var i ResolvedRoute
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.Ip,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}
