// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rules.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRule = `-- name: CreateRule :one
INSERT INTO routing_rules (profile_id, provider_id, rule_type, value, enabled, priority, description)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, profile_id, provider_id, rule_type, value, enabled, priority, description, created_at, updated_at
`

type CreateRuleParams struct {
	ProfileID   pgtype.UUID `json:"profile_id"`
	ProviderID  pgtype.UUID `json:"provider_id"`
	RuleType    RuleType    `json:"rule_type"`
	Value       string      `json:"value"`
	Enabled     bool        `json:"enabled"`
	Priority    int32       `json:"priority"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (RoutingRule, error) {
	row := q.db.QueryRow(ctx, createRule,
		arg.ProfileID,
		arg.ProviderID,
		arg.RuleType,
		arg.Value,
		arg.Enabled,
		arg.Priority,
		arg.Description,
	)
	var i RoutingRule
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ProviderID,
		&i.RuleType,
		&i.Value,
		&i.Enabled,
		&i.Priority,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRule = `-- name: DeleteRule :exec
DELETE FROM routing_rules WHERE id = $1
`

func (q *Queries) DeleteRule(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRule, id)
	return err
}

const getRule = `-- name: GetRule :one
SELECT id, profile_id, provider_id, rule_type, value, enabled, priority, description, created_at, updated_at FROM routing_rules WHERE id = $1
`

func (q *Queries) GetRule(ctx context.Context, id pgtype.UUID) (RoutingRule, error) {
	row := q.db.QueryRow(ctx, getRule, id)
	var i RoutingRule
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ProviderID,
		&i.RuleType,
		&i.Value,
		&i.Enabled,
		&i.Priority,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRulesByProvider = `-- name: GetRulesByProvider :many
SELECT id, profile_id, provider_id, rule_type, value, enabled, priority, description, created_at, updated_at FROM routing_rules WHERE provider_id = $1 AND enabled = true
`

func (q *Queries) GetRulesByProvider(ctx context.Context, providerID pgtype.UUID) ([]RoutingRule, error) {
	rows, err := q.db.Query(ctx, getRulesByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoutingRule{}
	for rows.Next() {
		var i RoutingRule
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.ProviderID,
			&i.RuleType,
			&i.Value,
			&i.Enabled,
			&i.Priority,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledDomainRules = `-- name: ListEnabledDomainRules :many
SELECT r.id, r.profile_id, r.provider_id, r.rule_type, r.value, r.enabled, r.priority, r.description, r.created_at, r.updated_at, p.provider_type, p.name as provider_name
FROM routing_rules r
LEFT JOIN vpn_providers p ON r.provider_id = p.id
WHERE r.enabled = true
  AND r.rule_type IN ('domain', 'domain_suffix', 'domain_keyword')
`

type ListEnabledDomainRulesRow struct {
	ID           pgtype.UUID        `json:"id"`
	ProfileID    pgtype.UUID        `json:"profile_id"`
	ProviderID   pgtype.UUID        `json:"provider_id"`
	RuleType     RuleType           `json:"rule_type"`
	Value        string             `json:"value"`
	Enabled      bool               `json:"enabled"`
	Priority     int32              `json:"priority"`
	Description  pgtype.Text        `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ProviderType NullProviderType   `json:"provider_type"`
	ProviderName pgtype.Text        `json:"provider_name"`
}

func (q *Queries) ListEnabledDomainRules(ctx context.Context) ([]ListEnabledDomainRulesRow, error) {
	rows, err := q.db.Query(ctx, listEnabledDomainRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledDomainRulesRow{}
	for rows.Next() {
		var i ListEnabledDomainRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.ProviderID,
			&i.RuleType,
			&i.Value,
			&i.Enabled,
			&i.Priority,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderType,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledRulesByProfile = `-- name: ListEnabledRulesByProfile :many
SELECT r.id, r.profile_id, r.provider_id, r.rule_type, r.value, r.enabled, r.priority, r.description, r.created_at, r.updated_at, p.provider_type, p.name as provider_name
FROM routing_rules r
LEFT JOIN vpn_providers p ON r.provider_id = p.id
WHERE r.profile_id = $1 AND r.enabled = true
ORDER BY r.priority ASC NULLS LAST
`

type ListEnabledRulesByProfileRow struct {
	ID           pgtype.UUID        `json:"id"`
	ProfileID    pgtype.UUID        `json:"profile_id"`
	ProviderID   pgtype.UUID        `json:"provider_id"`
	RuleType     RuleType           `json:"rule_type"`
	Value        string             `json:"value"`
	Enabled      bool               `json:"enabled"`
	Priority     int32              `json:"priority"`
	Description  pgtype.Text        `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ProviderType NullProviderType   `json:"provider_type"`
	ProviderName pgtype.Text        `json:"provider_name"`
}

func (q *Queries) ListEnabledRulesByProfile(ctx context.Context, profileID pgtype.UUID) ([]ListEnabledRulesByProfileRow, error) {
	rows, err := q.db.Query(ctx, listEnabledRulesByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledRulesByProfileRow{}
	for rows.Next() {
		var i ListEnabledRulesByProfileRow
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.ProviderID,
			&i.RuleType,
			&i.Value,
			&i.Enabled,
			&i.Priority,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderType,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRulesByProfile = `-- name: ListRulesByProfile :many
SELECT id, profile_id, provider_id, rule_type, value, enabled, priority, description, created_at, updated_at FROM routing_rules
WHERE profile_id = $1
ORDER BY priority ASC NULLS LAST, created_at ASC
`

// Правила маршрутизации
func (q *Queries) ListRulesByProfile(ctx context.Context, profileID pgtype.UUID) ([]RoutingRule, error) {
	rows, err := q.db.Query(ctx, listRulesByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoutingRule{}
	for rows.Next() {
		var i RoutingRule
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.ProviderID,
			&i.RuleType,
			&i.Value,
			&i.Enabled,
			&i.Priority,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRule = `-- name: UpdateRule :one
UPDATE routing_rules
SET provider_id  = COALESCE($2, provider_id),
    rule_type    = COALESCE($3, rule_type),
    value        = COALESCE($4, value),
    enabled      = COALESCE($5, enabled),
    priority     = COALESCE($6, priority),
    description  = COALESCE($7, description),
    updated_at   = now()
WHERE id = $1
RETURNING id, profile_id, provider_id, rule_type, value, enabled, priority, description, created_at, updated_at
`

type UpdateRuleParams struct {
	ID          pgtype.UUID `json:"id"`
	ProviderID  pgtype.UUID `json:"provider_id"`
	RuleType    RuleType    `json:"rule_type"`
	Value       string      `json:"value"`
	Enabled     bool        `json:"enabled"`
	Priority    int32       `json:"priority"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) (RoutingRule, error) {
	row := q.db.QueryRow(ctx, updateRule,
		arg.ID,
		arg.ProviderID,
		arg.RuleType,
		arg.Value,
		arg.Enabled,
		arg.Priority,
		arg.Description,
	)
	var i RoutingRule
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ProviderID,
		&i.RuleType,
		&i.Value,
		&i.Enabled,
		&i.Priority,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
